name: "Task"
description: "Create a task associated with a story or as a standalone work item."
title: "[Task] "
labels:
  - "type:task"
body:
  - type: markdown
    attributes:
      value: "Use tasks for subtasks or independent pieces of work."
  - type: input
    id: summary
    attributes:
      label: "Short summary"
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe what needs to be done"
      required: true
  - type: input
    id: parent
    attributes:
      label: "Parent story (optional)"
      description: "Link to parent story issue number or URL (e.g. #123)"
  - type: dropdown
    id: estimate
    attributes:
      label: "Estimate"
      options:
        - "0.25"
        - "0.5"
        - "1"
        - "2"
        - "3"
        - "Unestimated"
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "critical"
        - "high"
        - "medium"
        - "low"
  - type: assignees
    id: assignees
    attributes:
      label: "Assignees"